### ISSUE TITLE
InternalsVisibleTo assembly attribute in F# project does not work 

### ISSUE THREAD

**Issue by NinoFloris** [JetBrains/resharper-fsharp#335]
Since this issue was opened https://youtrack.jetbrains.com/issue/RIDER-44439 I could always work around it by defining IVT  attributes in the F# project *code* instead of msbuild to let Rider pick up the IVT status in dependent C#/F# projects. Since .NET 6.0? neither IVT attributes nor the MSBuild approach flows to dependent projects if the defining project is F#.

Building the solution actually works, it's just IDE errors and autocomplete not picking up on this.
IVT also still works for C#, and after some testing even the IVT MSBuild include seems to work (Might be a reason to close the youtrack sometime soon).

Simple repro is creating one C# console app depending on one F# library project, define an internal class in the F# project, add an IVT for the C# project and try to construct it from the C# one.

**Comment by NinoFloris** [comment]
@auduchinok I've pushed the project instead, I hope you can take a look.

https://github.com/NinoFloris/IVT-rider-repro

**Comment by auduchinok** [comment]
@NinoFloris Thanks a lot for the repro, I'll take a look soon!

**Comment by auduchinok** [comment]
Here's some progress:

<img width="421" alt="Screenshot 2022-01-20 at 18 29 25" src="https://user-images.githubusercontent.com/3923587/150369342-e0ac68ea-49c9-46d3-90bc-96df91b2914c.png">

It uses several hacks, and it looks like I'll have to keep some of them until a considerable amount of work is done properly, but this implementation might be good enough for now as a workaround, since that big work is planned (and some of it is already done).

**Comment by NinoFloris** [comment]
OK, that already looks pretty good! 

I forgot to clarify earlier that F# to F# also seems broken when it comes to respecting IVT in tooling, probably makes sense to you, just making sure you know.

**Comment by auduchinok** [comment]
@NinoFloris Thanks again for reminding about it!

Fixed in:
* [c58609f](https://github.com/JetBrains/resharper-fsharp/commit/c58609f3c257aa645b9259357d8a4086f9f7e96d): fixes including generated AssemblyInfo.fs files into analysis
* [4e53681](https://github.com/JetBrains/resharper-fsharp/commit/4e53681c3839978d6f4fc0b53d578caab78b602f): provides the attributes to the project model using questionable approach

**Comment by NinoFloris** [comment]
Fantastic! Thanks for such a quick merge of the fixes

**Comment by auduchinok** [comment]
Just for the record, F#->F# and C#->F# also works:

<img width="482" alt="Screenshot 2022-01-23 at 18 00 32" src="https://user-images.githubusercontent.com/3923587/150684705-7769581a-2031-4b38-861d-ef92dcd799f9.png">
