### ISSUE TITLE
Remove redundant parens on return statements

### ISSUE THREAD

**Issue by bartelink** [JetBrains/resharper-fsharp#336]
Given code within an `async` block such as:

    let deltas = Array.concat versionsByTranche
    return deltas

Applying Inline Variable refactor converts that to:

        return (Array.concat versionsByTranche)

It should either be possible to have the parentheses not be introduced in the first place, or be able to have the redundant parens be [highlighted and] removed via the remove redundant parens inspection. (Adding a second set of parens around the above ones correctly highlights and offers the fix).

----

The minimal repro seems to be:

    member _.A = async {
        let xs = [| [||]
                         [||] } 
        let t = Array.concat xs
        return t
    }

(note that Array.concat is `'T seq -> 'T[]`, although changing `xs` to be a `seq` expr does not change matters)

Rider Ver 2021.3.2 on Mac

**Comment by auduchinok** [comment]
> It should either be possible to have the parentheses not be introduced in the first place, or be able to have the redundant parens be [highlighted and] removed via the remove redundant parens inspection.

Yes, this is what we're going to do, thanks. Right now we have somewhat limited rules for different expression types permutations, and it acts in a defensive way in cases that aren't explicitly supported, since it's better to add redundant parens than to break the code during the refactoring. F# 6 simplifies things with its [refined undentation rules](https://github.com/fsharp/fslang-design/blob/main/FSharp-6.0/FS-1108-undentation-frenzy.md), so it'd be easier to support more expression types for projects targeting F# 6 and beyond.

**Comment by auduchinok** [comment]
Supporting`yield`/`return` expressions turned out to be quite straightforward, though! I've added handling for it in [25e9d60](https://github.com/JetBrains/resharper-fsharp/commit/25e9d60f3b751ac70ae38420478245c6e851707b). Thanks for writing about it!

Please report other cases where some code modification is suboptimal too: some of them could be as easy to fix, and others would be good test case candidates to take into account in future.
