### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by ShalokShalom** [JetBrains/resharper-fsharp#361]
Hi there :)

Due to being new to the Jetbrains community?

Why is it, that this tool is only available due to self-building?

I see it not on the market place: 

![Screenshot_57](https://user-images.githubusercontent.com/6344099/161229765-ebba7e12-3b39-4a0b-a4c3-06bc0e6c5190.png)

There is also no comment to why. 
Is it, because you like people to buy Rider?

**Comment by citizenmatt** [comment]
Hi! Looking at the image, that's the plugins settings page for IntelliJ IDEA. This project is a plugin bundled Rider, and isn't compatible with IntelliJ IDEA, so it won't show up in IDEA.

It's not compatible with IntelliJ IDEA because it requires a lot of things that are only available in Rider, such as the Visual Studio/msbuild based project model, the dotnet build system, dotnet debugger and so on. It's also heavily based on Rider's architecture, where UI facing features are implemented as a JVM-based IntelliJ based plugin, and dotnet language processing features are implemented in .NET and run in an external process based on the ReSharper plugin for Visual Studio. This means it can't run in IDEA, and requires Rider, where it's already bundled.

**Comment by ShalokShalom** [comment]
Well, so you mean "building" and not, how usually, "building (and using) in this section: 

![Screenshot_118](https://user-images.githubusercontent.com/6344099/161353599-0b81b34e-bf17-48e2-8a11-df6bcdbf68c8.png)


https://github.com/JetBrains/resharper-fsharp#building-the-plugin

**Comment by citizenmatt** [comment]
This project is F# support in Rider. It requires Rider to run. When you build it, Gradle will download a version of Rider to use as an SDK, then `./gradlew runIde` will run this SDK version of Rider to host and test the plug-in.

Since this plug-in is bundled with Rider, it can't be built and installed separately, but it can be built, developed and tested in an SDK version of Rider. This is downloaded by Gradle, so Rider is an optional dependency for building the plug-in.
