### ISSUE TITLE
When applying formatting sometimes the file jump to the bottom

### ISSUE THREAD

**Issue by MangelMaxime** [JetBrains/resharper-fsharp#403]
This break a lot the workflow because then I need find the line I was at.

https://user-images.githubusercontent.com/4760796/186752943-cb7a4410-d5d9-4247-8074-0a96b6fca592.mp4

Version: 2022.2
Build: RD-222.3345.139
OS: Windows

**Comment by auduchinok** [comment]
@DedSec256 Could you please check if this has been previously reported to YouTrack? I'm not sure if it's F#/Fantomas-specific.

**Comment by DedSec256** [comment]
@auduchinok, I didn't find any related issue, so I created [a new one](https://youtrack.jetbrains.com/issue/RIDER-81571/Formatting-a-large-file-causes-the-cursor-to-scroll-to-the-end)

**Comment by DedSec256** [comment]
Fixed in https://github.com/JetBrains/resharper-fsharp/pull/484. 
For now, the fix will work if a global/local Fantomas tool version >6.0.0-alpha-004 is used. When the release version of Fantomas 6 is released, we will update the built-in version of the formatter in the plugin and it will work out of the box.
