### ISSUE TITLE
How is plugin versioned currently?

### ISSUE THREAD

**Issue by En3Tho** [JetBrains/resharper-fsharp#758]
Earlier there were dedicated branches named after version e.g. net222, net223, etc. How is plugin versioned currently? Is there a commit hash that corresponds to version? I'm still maintaining that fork of mine with custom fcs and resharper-fsharp and it is sorta confusing now.

**Comment by auduchinok** [comment]
> How is plugin versioned currently?

The `main` GitHub branch is synchronized daily with `master` in the internal monorepo from where Rider is built. The release branches are handled in the monorepo now. The nightly SDK is built daily from `master` as well.

Previously plugin could often get broken due to changes in the monorepo, but now it's a part of the common build, so it's always green and bundled in nightly/dev builds, significantly simplifying the process when working on both GitHub and monorepo sides.

**Comment by En3Tho** [comment]
I see.. But I still do not understand how bugfixes are backported then, for example. Consider a scenario that `2024.3` has a bug and it is going to be fixed in `2024.3.1`. Can main actually "jump" far ahead to `xNext` instead? If it is then how to target a `2024.3.1` in such scenario considering that `main` can already be using some newer stuff from `xNext`?

**Comment by auduchinok** [comment]
> I see.. But I still do not understand how bugfixes are backported then, for example.

There're release branches created for minor releases, and we cherry-pick the needed changes using the internal merge infrastructure.

> Can main actually "jump" far ahead to xNext instead, like 2024.4 which is not compatible with 2024.3.1 anymore?

Yes, exactly. `main` targets the nightly SDK and release branches are created much earlier than EAP builds. This is the moment when the versions change.

> I guess you keep/maintain release branches internally now but how an external contributor can help in this scenario?

There should be no reason for an external developer to deal with an outdated release branch, since all the changes should flow to the upcoming versions first. Externals contributors shouldn't deal with cherry-picking such changes to the previous release branches either. The assumption here is people are going to use Release/EAP/nightly Rider builds from Toolbox, and not use a self-built plugin on a daily basis (or even maintain a fork of it).

I've asked the team about mirroring the release branches to GitHub, and it should in theory work soon, but it's not a scenario that we're going to support specifically. @En3Tho Please try to propose your changes to the compiler instead.
